In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./logs/default/version_4/metrics.csv')

In [3]:
df

    train_loss  epoch  step  val_loss
0     0.820931      0     4       NaN
1     0.792189      0     9       NaN
2     0.776901      0    14       NaN
3          NaN      0    16  0.803634
4     0.807837      1    19       NaN
5     0.776548      1    24       NaN
6     0.798902      1    29       NaN
7          NaN      1    33  0.795124
8     0.793432      2    34       NaN
9     0.763764      2    39       NaN
10    0.689749      2    44       NaN
11    0.825346      2    49       NaN
12         NaN      2    50  0.787599
13    0.693095      3    54       NaN
14    0.751103      3    59       NaN
15    0.695880      3    64       NaN
16         NaN      3    67  0.784957
17    0.791777      4    69       NaN
18    0.767156      4    74       NaN
19    0.760050      4    79       NaN
20    0.756659      4    84       NaN
21         NaN      4    84  0.777543
22    0.852582      5    89       NaN
23    0.798669      5    94       NaN
24    0.780959      5    99       NaN
25         NaN      5   101  0.777003
26    0.720350      6   104       NaN
27    0.707468      6   109       NaN
28    0.721402      6   114       NaN
29         NaN      6   118  0.769068
30    0.843679      7   119       NaN
31    0.761611      7   124       NaN
32    0.748990      7   129       NaN
33    0.831134      7   134       NaN
34         NaN      7   135  0.762933
35    0.641095      8   139       NaN
36    0.738623      8   144       NaN
37    0.793804      8   149       NaN
38         NaN      8   152  0.758046
39    0.764013      9   154       NaN
40    0.832549      9   159       NaN
41    0.768551      9   164       NaN
42    0.683374      9   169       NaN
43         NaN      9   169  0.751480

In [4]:
!tar -cvf checkpoint.tar ./logs/default/version_4

./logs/default/version_4/
./logs/default/version_4/checkpoints/
./logs/default/version_4/checkpoints/epoch=9-step=169.ckpt
./logs/default/version_4/hparams.yaml
./logs/default/version_4/metrics.csv